"""initial metadata foundation

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "block_registry",
        sa.Column("block_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("public_metadata", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "length(trim(block_id)) > 0 AND length(trim(version)) > 0",
            name=op.f("ck_block_registry_identity"),
        ),
        sa.PrimaryKeyConstraint("block_id", "version", name=op.f("pk_block_registry")),
    )
    with op.batch_alter_table("block_registry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_block_registry_category"), ["category"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(trim(name)) BETWEEN 1 AND 128", name=op.f("ck_projects_name")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(trim(name)) BETWEEN 1 AND 128", name=op.f("ck_pipelines_name")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_pipelines_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_pipelines_project_id")),
    )
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pipelines_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "workspace_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("local_path", sa.String(), nullable=True),
        sa.Column("secret_reference", sa.String(), nullable=True),
        sa.CheckConstraint(
            "length(trim(resource_id)) > 0",
            name=op.f("ck_workspace_bindings_resource_id"),
        ),
        sa.CheckConstraint(
            "local_path IS NOT NULL OR secret_reference IS NOT NULL",
            name=op.f("ck_workspace_bindings_target"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workspace_bindings_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_bindings")),
        sa.UniqueConstraint(
            "project_id", "resource_id", name=op.f("uq_workspace_bindings_project_id")
        ),
    )
    with op.batch_alter_table("workspace_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workspace_bindings_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "pipeline_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("revision > 0", name=op.f("ck_pipeline_revisions_revision")),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_revisions_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_revisions")),
        sa.UniqueConstraint(
            "pipeline_id", "revision", name=op.f("uq_pipeline_revisions_pipeline_id")
        ),
    )
    with op.batch_alter_table("pipeline_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pipeline_revisions_pipeline_id"),
            ["pipeline_id"],
            unique=False,
        )

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_revision_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued','running','succeeded','failed','cancelled')",
            name=op.f("ck_runs_state"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR (started_at IS NOT NULL AND ended_at >= started_at)",
            name=op.f("ck_runs_times"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0", name=op.f("ck_runs_row_count")
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_revision_id"],
            ["pipeline_revisions.id"],
            name=op.f("fk_runs_pipeline_revision_id_pipeline_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_pipeline_revision_id"),
            ["pipeline_revision_id"],
            unique=False,
        )

    op.create_table(
        "output_endpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("artifact_ref", sa.String(length=128), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "format IN ('csv','parquet')", name=op.f("ck_output_endpoints_format")
        ),
        sa.CheckConstraint(
            "length(trim(artifact_ref)) > 0",
            name=op.f("ck_output_endpoints_artifact_ref"),
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_output_endpoints_row_count"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_output_endpoints_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_output_endpoints")),
        sa.UniqueConstraint(
            "run_id", "node_id", "name", name=op.f("uq_output_endpoints_run_id")
        ),
    )
    with op.batch_alter_table("output_endpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_output_endpoints_run_id"), ["run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("output_endpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_output_endpoints_run_id"))

    op.drop_table("output_endpoints")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_pipeline_revision_id"))

    op.drop_table("runs")
    with op.batch_alter_table("pipeline_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_revisions_pipeline_id"))

    op.drop_table("pipeline_revisions")
    with op.batch_alter_table("workspace_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_bindings_project_id"))

    op.drop_table("workspace_bindings")
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipelines_project_id"))

    op.drop_table("pipelines")
    op.drop_table("projects")
    with op.batch_alter_table("block_registry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_block_registry_category"))

    op.drop_table("block_registry")
    # ### end Alembic commands ###
